#ifndef CONTROLMODE_H
#define CONTROLMODE_H

enum ControlMode {
    CONTROL_CHASER = 0,
    CONTROL_CYCLE_SET,
    CONTROL_CYCLE_FADE,
    CONTROL_CYCLE_FLASH,
    CONTROL_TWINKLE,
    CONTROL_GLOW,
    CONTROL_FLASH,
    CONTROL_FLASH_WHITE
};

#endif /* CONTROLMODE_H */
