#ifndef JSON_H
#define JSON_H

#include <QVariant>
#include <QString>

namespace QtJson
{


    // Parse a JSON string
    QVariant parse(const QString &json);

    QVariant parse(const QString &json, bool &success);
    
    
    // This method generates a textual JSON representation
    // \param data The JSON data generated by the parser.
    // \return QByteArray Textual JSON representation in UTF-8
    QByteArray serialize(const QVariant &data);

    QByteArray serialize(const QVariant &data, bool &success);


    // This method generates a textual JSON representation
    // \param data The JSON data generated by the parser.
    // \return QString Textual JSON representation
    QString serializeStr(const QVariant &data);

    QString serializeStr(const QVariant &data, bool &success);

} // end namespace

#endif // JSON_H
